# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build lambda source
        working-directory: src/lambda
        run: |
          npm install
          npm run build

  deploy:
    needs: build
    
    environment:
      name: Production

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Configure AWS Credentials based on environment variables 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-southeast-2

      # Runs a set of commands using the runners shell
      - name: Deploy Infrastructure to AWS
        env:
             CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
             CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
        run: |
          npm install
          npm run build
          npm run deploy:cd
